// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYDjHQLAp5fvUNnqHNJa9HHkaUvJ8JF4',
    appId: '1:248658899118:web:0fe7845dc9264fb4827d3f',
    messagingSenderId: '248658899118',
    projectId: 'ts-training-demo',
    authDomain: 'ts-training-demo.firebaseapp.com',
    storageBucket: 'ts-training-demo.firebasestorage.app',
    measurementId: 'G-S8BQ3JM4G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwPAqs_cF25i_Ai5Yt3gaV80pdltDzjAk',
    appId: '1:248658899118:android:d793123bb1bf626b827d3f',
    messagingSenderId: '248658899118',
    projectId: 'ts-training-demo',
    storageBucket: 'ts-training-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCI2PHWIB0ratQDG5uJo8k6rhf3-wc1Vc',
    appId: '1:248658899118:ios:203020ad1b4d7c1a827d3f',
    messagingSenderId: '248658899118',
    projectId: 'ts-training-demo',
    storageBucket: 'ts-training-demo.firebasestorage.app',
    androidClientId: '248658899118-qlc9slqkb13409gbpk068hffpp9t8514.apps.googleusercontent.com',
    iosClientId: '248658899118-2t4aoi9d5jsppbccokh3nmj7e52ddc0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsTrainingDemoFb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCI2PHWIB0ratQDG5uJo8k6rhf3-wc1Vc',
    appId: '1:248658899118:ios:203020ad1b4d7c1a827d3f',
    messagingSenderId: '248658899118',
    projectId: 'ts-training-demo',
    storageBucket: 'ts-training-demo.firebasestorage.app',
    androidClientId: '248658899118-qlc9slqkb13409gbpk068hffpp9t8514.apps.googleusercontent.com',
    iosClientId: '248658899118-2t4aoi9d5jsppbccokh3nmj7e52ddc0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsTrainingDemoFb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYDjHQLAp5fvUNnqHNJa9HHkaUvJ8JF4',
    appId: '1:248658899118:web:755a4e8630db7da4827d3f',
    messagingSenderId: '248658899118',
    projectId: 'ts-training-demo',
    authDomain: 'ts-training-demo.firebaseapp.com',
    storageBucket: 'ts-training-demo.firebasestorage.app',
    measurementId: 'G-RKMWKX462C',
  );
}
